/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Blog {
  'id' : string,
  'title' : string,
  'content' : string,
  'publishDate' : string,
  'createdAt' : bigint,
  'slug' : string,
  'author' : string,
  'imageAlt' : string,
  'imageUrl' : string,
  'category' : string,
  'authorDesignation' : string,
}
export interface CreateBlogInput {
  'title' : string,
  'content' : string,
  'publishDate' : string,
  'slug' : string,
  'author' : string,
  'imageAlt' : string,
  'imageUrl' : string,
  'category' : string,
  'authorDesignation' : string,
}
export interface PaginatedBlogs { 'totalCount' : bigint, 'blogs' : Array<Blog> }
export interface UpdateBlogInput {
  'title' : string,
  'content' : string,
  'publishDate' : string,
  'slug' : string,
  'author' : string,
  'imageAlt' : string,
  'imageUrl' : string,
  'category' : string,
  'authorDesignation' : string,
}
export interface _SERVICE {
  'createBlog' : ActorMethod<
    [CreateBlogInput],
    { 'ok' : Blog } |
      { 'err' : string }
  >,
  'deleteBlog' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'getAllBlogs' : ActorMethod<[], Array<Blog>>,
  'getBlogBySlug' : ActorMethod<[string], [] | [Blog]>,
  'getBlogsPaginated' : ActorMethod<
    [bigint, bigint, string, string],
    PaginatedBlogs
  >,
  'updateBlog' : ActorMethod<
    [string, UpdateBlogInput],
    { 'ok' : Blog } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];