/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateBlogInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Text,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'imageAlt' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'authorDesignation' : IDL.Text,
});
export const Blog = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Text,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'imageAlt' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'authorDesignation' : IDL.Text,
});
export const PaginatedBlogs = IDL.Record({
  'totalCount' : IDL.Nat,
  'blogs' : IDL.Vec(Blog),
});
export const UpdateBlogInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Text,
  'slug' : IDL.Text,
  'author' : IDL.Text,
  'imageAlt' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'authorDesignation' : IDL.Text,
});

export const idlService = IDL.Service({
  'createBlog' : IDL.Func(
      [CreateBlogInput],
      [IDL.Variant({ 'ok' : Blog, 'err' : IDL.Text })],
      [],
    ),
  'deleteBlog' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAllBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
  'getBlogBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Blog)], ['query']),
  'getBlogsPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [PaginatedBlogs],
      ['query'],
    ),
  'updateBlog' : IDL.Func(
      [IDL.Text, UpdateBlogInput],
      [IDL.Variant({ 'ok' : Blog, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateBlogInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Text,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'imageAlt' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'authorDesignation' : IDL.Text,
  });
  const Blog = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Text,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'imageAlt' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'authorDesignation' : IDL.Text,
  });
  const PaginatedBlogs = IDL.Record({
    'totalCount' : IDL.Nat,
    'blogs' : IDL.Vec(Blog),
  });
  const UpdateBlogInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Text,
    'slug' : IDL.Text,
    'author' : IDL.Text,
    'imageAlt' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'authorDesignation' : IDL.Text,
  });
  
  return IDL.Service({
    'createBlog' : IDL.Func(
        [CreateBlogInput],
        [IDL.Variant({ 'ok' : Blog, 'err' : IDL.Text })],
        [],
      ),
    'deleteBlog' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAllBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
    'getBlogBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Blog)], ['query']),
    'getBlogsPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [PaginatedBlogs],
        ['query'],
      ),
    'updateBlog' : IDL.Func(
        [IDL.Text, UpdateBlogInput],
        [IDL.Variant({ 'ok' : Blog, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };